// Authentification
export const LOGIN ="LOGIN" 
export const LOGOUT ="LOGOUT"  
export const REGISTER="REGISTER" 
export const SETLOADING="SETLOADING" 
export const AUTHERROR="AUTHERROR" 
export const GET_AUTH_USER="GET_AUTH_USER" 
 
// Updating Model Users

export const EDIT_USER= "EDIT_USER"
export const DELETE_USER= "DELETE_USER"

// FOR  ALL ProductS Model
export const GET_ALL_PRODUCTS_REQUEST= "GET_ALL_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SECCESS= "GET_PRODUCTS_SECCESS"
export const GET_PRODUCTS_FAIL= "GET_PRODUCTS_FAIL"
// Product details
export const GET_PRODUCT_REQUEST= "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SECCESS= "GET_PRODUCT_SECCESS"
export const GET_PRODUCT_FAIL= "GET_PRODUCT_FAIL"
export const GET_PRODUCT_RESET= "GET_PRODUCT_RESET"

// For the card
export const ADD_TO_CART= "ADD_TO_CART"
export const REMOVE_FROM_CART= "REMOVE_FROM_CART"
export const CART_RESET= "CART_RESET"

// export const DELETE_USER= "DELETE_USER"
// export const DELETE_USER= "DELETE_USER"


// FOR  ALL CATEGORIES Model
export const GET_ALL_CATEGORIES_REQUEST= "GET_ALL_CATEGORIES_REQUEST"
export const GET_CATEGORIES_SECCESS= "GET_CATEGORIES_SECCESS"
export const GET_CATEGORIES_FAIL= "GET_CATEGORIES_FAIL"

// get Products by Categorie
export const GET_CATEGORIE_PRODUCTS_REQUEST= "GET_CATEGORIE_PRODUCTS_REQUEST"
export const GET_CATEGORIE_PRODUCTS_SECCESS= "GET_CATEGORIE_PRODUCTS_SECCESS"
export const GET_CATEGORIE_PRODUCTS_FAIL= "GET_CATEGORIE_PRODUCTS_FAIL"


// Categorie details
export const GET_CATEGORIE_REQUEST= "GET_CATEGORIE_REQUEST"
export const GET_CATEGORIE_SECCESS= "GET_CATEGORIE_SECCESS"
export const GET_CATEGORIE_FAIL= "GET_CATEGORIE_FAIL"
export const GET_CATEGORIE_RESET= "GET_CATEGORIE_RESET"

// Messages
export const GET_UNREADED_MESSAGES="GET_UNREADED_MESSAGES"
export const GET_All_MESSAGES="GET_All_MESSAGES"

// ALL ORDERS

export const GET_ALL_ORDERS_REQUEST= "GET_ALL_ORDERS_REQUEST"
export const GET_ORDERS_SECCESS= "GET_ORDERS_SECCESS"
export const GET_ORDERS_FAIL= "GET_ORDERS_FAIL"

// ORDER details
export const GET_ORDER_REQUEST= "GET_ORDER_REQUEST"
export const GET_ORDER_SECCESS= "GET_ORDER_SECCESS"
export const GET_ORDER_FAIL= "GET_ORDER_FAIL"
export const GET_ORDER_RESET= "GET_ORDER_RESET"

// GET ONE COMMAND
// POST COMMAND 
export const ADD_COMMAND_REQUEST= "ADD_COMMAND_REQUEST"
export const ADD_COMMAND_SUCCESS= "ADD_COMMAND_SUCCESS"
export const ADD_COMMAND_FAILED= "ADD_COMMAND_FAILED"
export const REMOVE_COMMAND= "REMOVE_COMMAND"
export const EDIT_COMMAND= "EDIT_COMMAND"
// export const ADD_CATEGORIE= "ADD_CATEGORIE"
// ADD 


// FOR  ALL MARQUES Model
export const GET_ALL_MARQUES_REQUEST= "GET_ALL_MARQUES_REQUEST"
export const GET_MARQUES_SECCESS= "GET_MARQUES_SECCESS"
export const GET_MARQUES_FAIL= "GET_MARQUES_FAIL"

// MARQUE details
export const GET_MARQUE_REQUEST= "GET_MARQUE_REQUEST"
export const GET_MARQUE_SECCESS= "GET_MARQUE_SECCESS"
export const GET_MARQUE_FAIL= "GET_MARQUE_FAIL"
export const GET_MARQUE_RESET= "GET_MARQUE_RESET"

// get Products by MARQUE
export const GET_MARQUE_PRODUCTS_REQUEST= "GET_MARQUE_PRODUCTS_REQUEST"
export const GET_MARQUE_PRODUCTS_SECCESS= "GET_MARQUE_PRODUCTS_SECCESS"
export const GET_MARQUE_PRODUCTS_FAIL= "GET_MARQUE_PRODUCTS_FAIL"

// FOR  ALL USERS Model
export const GET_ALL_USERS_REQUEST= "GET_ALL_USERS_REQUEST"
export const GET_USERS_SECCESS= "GET_USERS_SECCESS"
export const GET_USERS_FAIL= "GET_USERS_FAIL"

// USER details
export const GET_USER_REQUEST= "GET_USER_REQUEST"
export const GET_USER_SECCESS= "GET_USER_SECCESS"
export const GET_USER_FAIL= "GET_USER_FAIL"
export const GET_USER_RESET= "GET_USER_RESET"
